// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bktmvcjhpzfpdtwqyxla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdG12Y2pocHpmcGR0d3F5eGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzMzNTMsImV4cCI6MjA2OTQ0OTM1M30.V_ANp0FW9-NGPOkgVZQ1CU-rnl6b-tQCTr27aE7qwIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});