// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwvzgmewewxytpsgsrts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3dnpnbWV3ZXd4eXRwc2dzcnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzA0MjIsImV4cCI6MjA3MDUwNjQyMn0.j7YUBPG1-Ga6L3ypB60TVMWtlWWz09ziyPVDDXeI2JI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});